# conda env create -f environment-dev.yml

name: PAVICS-landing
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - gitpython
  - jupyter
  - nbconvert
  # then `pre-commit install` to initialize
  - pre-commit
